### ISSUE TITLE
.github/workflows/develop.yml 토큰 수정

### ISSUE THREAD

**Issue by 1haann** [Auction-shop-project/As_BE#21]
## 목적
> develop 브랜치로 PullRequest 생성 시 workflow 실행이 되지 않는 문제 발생과 해결 방법

## 작업 상세 내용
> .github/workflows/develop.yml 파일의 내용 수정
> 변경 전 매개 변수명 : TOKEN 
> 변경 후 매개 변수명 : GH_TOKEN
```yml
jobs:
  build:
    steps:
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## 참고 사항
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
